import { StepType, type PromptChain, type PromptStep, parameterNameList } from "./chains";
import { PredictionService, defaultPredictionSettings } from "./services";

export function getDefaultChain(): PromptChain {
    return {
        version: 5,
        title: "Untitled Chain",
        parametersDict: {storyTopic: "time travelling", maxWords: "50"},
        steps: [
            getDefaultStep()
        ]
    }
}

function getDefaultStep(): PromptStep {
    return {
        stepType: StepType.prompt,
        promptText: "{# This is an example prompt: replace it with your own! #}\n\nTell me a short (less than {{ maxWords }} words) story about {{ storyTopic }}.\n\n{% if anotherTopic %}\nAnd another one about {{ anotherTopic | upper }}!!!\n{% endif %}",
        title:  "Untitled Prompt",
        resultKey: "result_0",
        results: null,
        minimized: false,
        predictionService: PredictionService.openai,
        predictionSettings: defaultPredictionSettings()
    }
}

function getExampleAddedStep(promptChain: PromptChain, position: number): PromptStep {
    let result = getDefaultStep();
    let i = 0;
    let resultKey = null;
    const existingParamNames = new Set(parameterNameList(promptChain, true));
    while (! resultKey) {
        let candidateKey = "result_" + i;
        if (! existingParamNames.has(candidateKey)) resultKey = candidateKey;
        i++;
    }
    result.resultKey = resultKey;

    // Customise example based on the new prompt position
    if (position == 0) result.promptText = "{# This is an example additional step: try using its result key as a variable in the next ones! #}\n\nProduce a JSON object describing the properties of a character in a story about {{ storyTopic }}"
    else {
        const previousResultKey = promptChain.steps[position-1].resultKey
        result.promptText = "{# This is an example additional step: you can use previous result keys here! #}\n\nProduce a short poem about the following text that was generated by an AI model:\n\n{{"+previousResultKey+"}}";
    }

    return result;
}

export function addChainStep(promptChain: PromptChain, position: number) : void {
    
    promptChain.steps.splice(position, 0, getExampleAddedStep(promptChain, position));
}

export function deleteChainStep(promptChain: PromptChain, position: number) : void {
    promptChain.steps.splice(position, 1);
}

export function moveChainStep(promptChain: PromptChain, sourcePosition: number, targetPosition: number) : void {
    let step = promptChain.steps[sourcePosition];
    promptChain.steps.splice(sourcePosition, 1);
    promptChain.steps.splice(targetPosition, 0, step);
}
